# Copyright 2022-2026 XProbe Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from pathlib import Path

XINFERENCE_ENV_ENDPOINT = "XINFERENCE_ENDPOINT"
XINFERENCE_ENV_MODEL_SRC = "XINFERENCE_MODEL_SRC"
XINFERENCE_ENV_CSG_TOKEN = "XINFERENCE_CSG_TOKEN"
XINFERENCE_ENV_CSG_ENDPOINT = "XINFERENCE_CSG_ENDPOINT"
XINFERENCE_ENV_HOME_PATH = "XINFERENCE_HOME"
XINFERENCE_ENV_HEALTH_CHECK_FAILURE_THRESHOLD = (
    "XINFERENCE_HEALTH_CHECK_FAILURE_THRESHOLD"
)
XINFERENCE_ENV_HEALTH_CHECK_INTERVAL = "XINFERENCE_HEALTH_CHECK_INTERVAL"
XINFERENCE_ENV_HEALTH_CHECK_TIMEOUT = "XINFERENCE_HEALTH_CHECK_TIMEOUT"
XINFERENCE_ENV_TCP_REQUEST_TIMEOUT = "XINFERENCE_TCP_REQUEST_TIMEOUT"
# Supervisor -> Worker RPC bounds
XINFERENCE_ENV_LIST_MODELS_PER_WORKER_TIMEOUT = (
    "XINFERENCE_LIST_MODELS_PER_WORKER_TIMEOUT"
)
XINFERENCE_ENV_GET_MODEL_RPC_TIMEOUT = "XINFERENCE_GET_MODEL_RPC_TIMEOUT"
XINFERENCE_ENV_STATUS_GATHER_TIMEOUT = "XINFERENCE_STATUS_GATHER_TIMEOUT"
XINFERENCE_ENV_STATUS_REPORT_MULTIPLIER = "XINFERENCE_STATUS_REPORT_MULTIPLIER"
XINFERENCE_ENV_DISABLE_HEALTH_CHECK = "XINFERENCE_DISABLE_HEALTH_CHECK"
XINFERENCE_ENV_DISABLE_METRICS = "XINFERENCE_DISABLE_METRICS"
XINFERENCE_ENV_DOWNLOAD_MAX_ATTEMPTS = "XINFERENCE_DOWNLOAD_MAX_ATTEMPTS"
XINFERENCE_ENV_TEXT_TO_IMAGE_BATCHING_SIZE = "XINFERENCE_TEXT_TO_IMAGE_BATCHING_SIZE"
XINFERENCE_ENV_VIRTUAL_ENV = "XINFERENCE_ENABLE_VIRTUAL_ENV"
XINFERENCE_ENV_VIRTUAL_ENV_SKIP_INSTALLED = "XINFERENCE_VIRTUAL_ENV_SKIP_INSTALLED"
XINFERENCE_ENV_SSE_PING_ATTEMPTS_SECONDS = "XINFERENCE_SSE_PING_ATTEMPTS_SECONDS"
XINFERENCE_ENV_MAX_TOKENS = "XINFERENCE_MAX_TOKENS"
XINFERENCE_ENV_ALLOWED_IPS = "XINFERENCE_ALLOWED_IPS"
XINFERENCE_ENV_BATCH_SIZE = "XINFERENCE_BATCH_SIZE"
XINFERENCE_ENV_BATCH_INTERVAL = "XINFERENCE_BATCH_INTERVAL"
XINFERENCE_ENV_ALLOW_MULTI_REPLICA_PER_GPU = "XINFERENCE_ALLOW_MULTI_REPLICA_PER_GPU"
XINFERENCE_ENV_LAUNCH_STRATEGY = "XINFERENCE_LAUNCH_STRATEGY"

# OTEL environment variable names
XINFERENCE_ENV_ENABLE_OTEL = "XINFERENCE_ENABLE_OTEL"
XINFERENCE_ENV_OTLP_TRACE_ENDPOINT = "XINFERENCE_OTLP_TRACE_ENDPOINT"
XINFERENCE_ENV_OTLP_METRIC_ENDPOINT = "XINFERENCE_OTLP_METRIC_ENDPOINT"
XINFERENCE_ENV_OTLP_BASE_ENDPOINT = "XINFERENCE_OTLP_BASE_ENDPOINT"
XINFERENCE_ENV_OTLP_API_KEY = "XINFERENCE_OTLP_API_KEY"
XINFERENCE_ENV_OTEL_EXPORTER_OTLP_PROTOCOL = "XINFERENCE_OTEL_EXPORTER_OTLP_PROTOCOL"
XINFERENCE_ENV_OTEL_EXPORTER_TYPE = "XINFERENCE_OTEL_EXPORTER_TYPE"
XINFERENCE_ENV_OTEL_SAMPLING_RATE = "XINFERENCE_OTEL_SAMPLING_RATE"
XINFERENCE_ENV_OTEL_BATCH_EXPORT_SCHEDULE_DELAY = (
    "XINFERENCE_OTEL_BATCH_EXPORT_SCHEDULE_DELAY"
)
XINFERENCE_ENV_OTEL_MAX_QUEUE_SIZE = "XINFERENCE_OTEL_MAX_QUEUE_SIZE"
XINFERENCE_ENV_OTEL_MAX_EXPORT_BATCH_SIZE = "XINFERENCE_OTEL_MAX_EXPORT_BATCH_SIZE"
XINFERENCE_ENV_OTEL_METRIC_EXPORT_INTERVAL = "XINFERENCE_OTEL_METRIC_EXPORT_INTERVAL"
XINFERENCE_ENV_OTEL_BATCH_EXPORT_TIMEOUT = "XINFERENCE_OTEL_BATCH_EXPORT_TIMEOUT"
XINFERENCE_ENV_OTEL_METRIC_EXPORT_TIMEOUT = "XINFERENCE_OTEL_METRIC_EXPORT_TIMEOUT"


def get_xinference_home() -> str:
    home_path = os.environ.get(XINFERENCE_ENV_HOME_PATH)
    if home_path is None:
        home_path = str(Path.home() / ".xinference")
    # Always change huggingface, modelscope, and openmind_hub default download path
    # to ensure xinference process has write permissions for downloading dependencies
    # (e.g., Qwen3-ASR's forced aligner model downloaded from Hugging Face Hub)
    os.environ["HUGGINGFACE_HUB_CACHE"] = os.path.join(home_path, "huggingface")
    os.environ["MODELSCOPE_CACHE"] = os.path.join(home_path, "modelscope")
    os.environ["XDG_CACHE_HOME"] = os.path.join(home_path, "openmind_hub")
    # In multi-tenant mode,
    # gradio's temporary files are stored in their respective home directories,
    # to prevent insufficient permissions
    os.environ["GRADIO_TEMP_DIR"] = os.path.join(home_path, "tmp", "gradio")
    return home_path


XINFERENCE_HOME = get_xinference_home()
XINFERENCE_CACHE_DIR = os.path.join(XINFERENCE_HOME, "cache")
XINFERENCE_TENSORIZER_DIR = os.path.join(XINFERENCE_HOME, "tensorizer")
XINFERENCE_MODEL_DIR = os.path.join(XINFERENCE_HOME, "model")
XINFERENCE_LOG_DIR = os.path.join(XINFERENCE_HOME, "logs")
XINFERENCE_IMAGE_DIR = os.path.join(XINFERENCE_HOME, "image")
XINFERENCE_VIDEO_DIR = os.path.join(XINFERENCE_HOME, "video")
XINFERENCE_AUTH_DIR = os.path.join(XINFERENCE_HOME, "auth")
XINFERENCE_VIRTUAL_ENV_DIR = os.path.join(XINFERENCE_HOME, "virtualenv")
XINFERENCE_CSG_ENDPOINT = str(
    os.environ.get(XINFERENCE_ENV_CSG_ENDPOINT, "https://hub-stg.opencsg.com/")
)

XINFERENCE_DEFAULT_LOCAL_HOST = "127.0.0.1"
XINFERENCE_DEFAULT_DISTRIBUTED_HOST = "0.0.0.0"
XINFERENCE_DEFAULT_ENDPOINT_PORT = 9997
XINFERENCE_DEFAULT_LOG_FILE_NAME = "xinference.log"
XINFERENCE_LOG_MAX_BYTES = 100 * 1024 * 1024
XINFERENCE_LOG_BACKUP_COUNT = 30
XINFERENCE_LOG_ARG_MAX_LENGTH = 100
XINFERENCE_HEALTH_CHECK_FAILURE_THRESHOLD = int(
    os.environ.get(XINFERENCE_ENV_HEALTH_CHECK_FAILURE_THRESHOLD, 5)
)
XINFERENCE_HEALTH_CHECK_INTERVAL = int(
    os.environ.get(XINFERENCE_ENV_HEALTH_CHECK_INTERVAL, 5)
)
XINFERENCE_HEALTH_CHECK_TIMEOUT = int(
    os.environ.get(XINFERENCE_ENV_HEALTH_CHECK_TIMEOUT, 10)
)
XINFERENCE_TCP_REQUEST_TIMEOUT = int(
    os.environ.get(XINFERENCE_ENV_TCP_REQUEST_TIMEOUT, 5)
)
# Per-worker list_models RPC; default well below TCP read-timeout (~600s+) seen in production
XINFERENCE_LIST_MODELS_PER_WORKER_TIMEOUT = int(
    os.environ.get(XINFERENCE_ENV_LIST_MODELS_PER_WORKER_TIMEOUT, "60")
)
# get_model -> worker_ref.get_model RPC
XINFERENCE_GET_MODEL_RPC_TIMEOUT = int(
    os.environ.get(XINFERENCE_ENV_GET_MODEL_RPC_TIMEOUT, "120")
)
XINFERENCE_DISABLE_HEALTH_CHECK = bool(
    int(os.environ.get(XINFERENCE_ENV_DISABLE_HEALTH_CHECK, 0))
)
XINFERENCE_DISABLE_METRICS = bool(
    int(os.environ.get(XINFERENCE_ENV_DISABLE_METRICS, 0))
)
XINFERENCE_DOWNLOAD_MAX_ATTEMPTS = int(
    os.environ.get(XINFERENCE_ENV_DOWNLOAD_MAX_ATTEMPTS, 3)
)
XINFERENCE_TEXT_TO_IMAGE_BATCHING_SIZE = os.environ.get(
    XINFERENCE_ENV_TEXT_TO_IMAGE_BATCHING_SIZE, None
)
XINFERENCE_SSE_PING_ATTEMPTS_SECONDS = int(
    os.environ.get(XINFERENCE_ENV_SSE_PING_ATTEMPTS_SECONDS, 600)
)
XINFERENCE_LAUNCH_MODEL_RETRY = 3
XINFERENCE_DEFAULT_CANCEL_BLOCK_DURATION = 30
XINFERENCE_ENABLE_VIRTUAL_ENV = bool(int(os.getenv(XINFERENCE_ENV_VIRTUAL_ENV, "1")))
XINFERENCE_VIRTUAL_ENV_SKIP_INSTALLED = bool(
    int(os.getenv(XINFERENCE_ENV_VIRTUAL_ENV_SKIP_INSTALLED, "1"))
)
XINFERENCE_MAX_TOKENS = os.getenv(XINFERENCE_ENV_MAX_TOKENS)
XINFERENCE_MAX_TOKENS = int(XINFERENCE_MAX_TOKENS) if XINFERENCE_MAX_TOKENS else None  # type: ignore
XINFERENCE_ALLOWED_IPS = os.getenv(XINFERENCE_ENV_ALLOWED_IPS)
XINFERENCE_BATCH_SIZE = int(os.getenv(XINFERENCE_ENV_BATCH_SIZE, "32"))
XINFERENCE_BATCH_INTERVAL = float(os.getenv(XINFERENCE_ENV_BATCH_INTERVAL, "0.003"))
XINFERENCE_ALLOW_MULTI_REPLICA_PER_GPU = bool(
    int(os.getenv(XINFERENCE_ENV_ALLOW_MULTI_REPLICA_PER_GPU, "1"))
)
XINFERENCE_LAUNCH_STRATEGY = os.getenv(
    XINFERENCE_ENV_LAUNCH_STRATEGY, "IDLE_FIRST_LAUNCH_STRATEGY"
)

# Status report multiplier: how many heartbeats before a full status report
# Default: 3 (report full status every 30 seconds with 10s heartbeat interval)
XINFERENCE_STATUS_REPORT_MULTIPLIER = int(
    os.environ.get(XINFERENCE_ENV_STATUS_REPORT_MULTIPLIER, 3)
)

# Status gather timeout in seconds (for collecting GPU info, etc.)
# Default: 10 seconds, increased from original 5 seconds
XINFERENCE_STATUS_GATHER_TIMEOUT = int(
    os.environ.get(XINFERENCE_ENV_STATUS_GATHER_TIMEOUT, 10)
)

# OTEL resolved values
XINFERENCE_ENABLE_OTEL = (
    os.getenv(XINFERENCE_ENV_ENABLE_OTEL, "false").strip().lower() == "true"
)
_XINFERENCE_OTLP_BASE_ENDPOINT = os.getenv(
    XINFERENCE_ENV_OTLP_BASE_ENDPOINT, "http://localhost:4318"
)
XINFERENCE_OTLP_TRACE_ENDPOINT = (
    os.getenv(XINFERENCE_ENV_OTLP_TRACE_ENDPOINT)
    or f"{_XINFERENCE_OTLP_BASE_ENDPOINT}/v1/traces"
)
XINFERENCE_OTLP_METRIC_ENDPOINT = (
    os.getenv(XINFERENCE_ENV_OTLP_METRIC_ENDPOINT)
    or f"{_XINFERENCE_OTLP_BASE_ENDPOINT}/v1/metrics"
)
XINFERENCE_OTLP_API_KEY = os.getenv(XINFERENCE_ENV_OTLP_API_KEY, "")
XINFERENCE_OTEL_EXPORTER_OTLP_PROTOCOL = os.getenv(
    XINFERENCE_ENV_OTEL_EXPORTER_OTLP_PROTOCOL, "http/protobuf"
)
XINFERENCE_OTEL_EXPORTER_TYPE = os.getenv(XINFERENCE_ENV_OTEL_EXPORTER_TYPE, "otlp")
XINFERENCE_OTEL_SAMPLING_RATE = float(
    os.getenv(XINFERENCE_ENV_OTEL_SAMPLING_RATE, "0.1")
)
XINFERENCE_OTEL_BATCH_EXPORT_SCHEDULE_DELAY = int(
    os.getenv(XINFERENCE_ENV_OTEL_BATCH_EXPORT_SCHEDULE_DELAY, "5000")
)
XINFERENCE_OTEL_MAX_QUEUE_SIZE = int(
    os.getenv(XINFERENCE_ENV_OTEL_MAX_QUEUE_SIZE, "2048")
)
XINFERENCE_OTEL_MAX_EXPORT_BATCH_SIZE = int(
    os.getenv(XINFERENCE_ENV_OTEL_MAX_EXPORT_BATCH_SIZE, "512")
)
XINFERENCE_OTEL_METRIC_EXPORT_INTERVAL = int(
    os.getenv(XINFERENCE_ENV_OTEL_METRIC_EXPORT_INTERVAL, "60000")
)
XINFERENCE_OTEL_BATCH_EXPORT_TIMEOUT = int(
    os.getenv(XINFERENCE_ENV_OTEL_BATCH_EXPORT_TIMEOUT, "10000")
)
XINFERENCE_OTEL_METRIC_EXPORT_TIMEOUT = int(
    os.getenv(XINFERENCE_ENV_OTEL_METRIC_EXPORT_TIMEOUT, "30000")
)
