FROM vllm/vllm-openai:v0.17.1-aarch64

COPY . /opt/inference

WORKDIR /opt/inference

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 18.20.4

RUN apt-get -y update \
  && apt install -y wget curl procps git libgl1 libfst-dev cmake libssl-dev \
  && apt-get -y update \
  && apt-get install -y --only-upgrade libstdc++6 && apt install -y libc6 \
  && mkdir -p $NVM_DIR \
  && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash \
  && . $NVM_DIR/nvm.sh \
  && nvm install $NODE_VERSION \
  && nvm alias default $NODE_VERSION \
  && nvm use default \
  && apt-get -yq clean

ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
ARG PIP_INDEX=https://pypi.org/simple

RUN apt-get update -y && \
    pip install --upgrade pip setuptools==79.0.1 wheel && \
    apt-get install -y wget libpcre3 libpcre3-dev gcc rsync zlib1g zlib1g-dev git libssl-dev && \
    apt-get clean all && \
    cd /opt/inference/ && \
    pip install --upgrade-strategy only-if-needed -r /opt/inference/xinference/deploy/docker/requirements_aarch64/requirements_aarch64.txt && \
    cd /opt/inference && \
    python3 setup.py build_web && \
    git restore . && \
    pip install -i "$PIP_INDEX" --no-deps --no-build-isolation "." && \
    pip install -i "$PIP_INDEX" "xllamacpp>=0.2.0" && \
    pip cache purge

RUN pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128 \
    --no-deps && \
    pip install triton && \
    pip install torchcodec && \
    pip install "numpy==2.2.6" && \
    pip cache purge

ENTRYPOINT []
