name: GPU Runner Check

on:
  workflow_dispatch:
  push:
    branches:
      - bld/adopt-gpu-larger-runner

jobs:
  inspect:
    runs-on: gpu-t4
    steps:
      - name: System info
        run: |
          echo "=== Arch / OS ==="
          uname -a

          echo "=== CPU ==="
          nproc
          lscpu

          echo "=== Memory ==="
          free -h

          echo "=== Disk ==="
          df -h
          
          echo "Before -------doing nothing----"
          ls -l
           
          echo "--------  Debug -------"
          wget https://cloudflare.com -O cloudflare_10mb.bin
          ls -al

          echo "=== GPU / CUDA ==="
          nvidia-smi
          nvcc --version || echo "nvcc not found"
